apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ APPLICATION_NAME }}-deployment
  labels:
    app: {{ APPLICATION_NAME }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ APPLICATION_NAME }}
  template:
    metadata:
      labels:
        app: {{ APPLICATION_NAME }}
    spec:
      containers:
        - name: {{ APPLICATION_NAME }}
          image: {{ K8S_IMAGE }}
          ports:
            {% for service in K8S_SERVICES.split(";") -%}
            {% set _,port,_=service.split(":") %}
            - containerPort: {{ port.upper() }}
            {%- endfor %}
          env:
            {% for environment in K8S_ENV_VARIABLES.split(";") -%}
            {% set key,value=environment.split(":") %}
            - name: {{ key }}
              value: {{ value }}
            {%- endfor %}
